security:
    enable_authenticator_manager: true
    providers:
        users:
            entity:
                class: 'App\Entity\User'
    firewalls:
        main:
            custom_authenticators:
                - App\Security\IpAddressAuthenticator
