version: '2'

services:
  app:
    build:
      context: ./
      dockerfile: docker/app/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    environment:
      - DATABASE_URL=mysql://root:secret@database:3306/wordsdb
    depends_on:
      - database

  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 33061:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

